"""Discovery registry: persists discovered-entity state in SQLite and writes
approved mappings / ignores to a generated overlay file (config/discovered.yaml)
that the config loader merges into devices.yaml.

We never edit the hand-written devices.yaml in place (preserves comments). We
never auto-delete or auto-ignore; ignores only happen on explicit user action.
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any, Optional

import yaml

from ..db.database import get_session
from ..db.models import DiscoveredEntity
from ..settings import get_settings
from .classifier import EntityClassification

logger = logging.getLogger("tpg.discovery.registry")

DISCOVERED_FILE = "discovered.yaml"
_LIST_SECTIONS = ["device_aliases", "cameras", "locks", "speakers", "displays",
                  "climate", "security_sensors", "personal_devices", "avoid",
                  "ignored"]


def _overlay_path() -> Path:
    return get_settings().config_path / DISCOVERED_FILE


def read_overlay() -> dict[str, Any]:
    path = _overlay_path()
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def write_overlay(data: dict[str, Any]) -> None:
    path = _overlay_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by TPG HomeAI discovery approvals. Safe to edit, "
                 "but it is merged into devices.yaml at load time.\n")
        yaml.safe_dump(data, fh, sort_keys=False, allow_unicode=True)


def _slug(entity_id: str) -> str:
    base = entity_id.split(".", 1)[-1]
    return re.sub(r"[^a-z0-9_]+", "_", base.lower()).strip("_") or "device"


# --------------------------------------------------------------------------
# SQLite sync of classifications
# --------------------------------------------------------------------------
def sync_classifications(classifications: list[EntityClassification]) -> None:
    """Upsert discovery rows. Preserves user decisions (approved/ignored)."""
    with get_session() as session:
        existing = {d.entity_id: d for d in session.query(DiscoveredEntity).all()}
        for c in classifications:
            row = existing.get(c.entity_id)
            if row is None:
                row = DiscoveredEntity(entity_id=c.entity_id)
                session.add(row)
            # Keep a previously-decided status (approved/ignored) sticky.
            decided = row.status in ("approved", "ignored")
            row.domain = c.domain
            row.friendly_name = c.friendly_name
            row.category = c.suggested_category
            if not decided:
                row.room = c.likely_room or ""
                row.risk_level = c.risk_level
                row.suggested_aliases = json.dumps(c.suggested_aliases)
                row.reason = c.reason
                row.status = "known" if c.status == "known" else (
                    row.status if row.status in ("approved", "ignored") else c.status)
            row.is_available = c.is_available
        session.commit()


def get_pending() -> list[dict[str, Any]]:
    with get_session() as session:
        rows = session.query(DiscoveredEntity).filter(
            DiscoveredEntity.status == "new").all()
        return [_row_dict(r) for r in rows]


def get_all() -> list[dict[str, Any]]:
    with get_session() as session:
        return [_row_dict(r) for r in session.query(DiscoveredEntity).all()]


def _row_dict(r: DiscoveredEntity) -> dict[str, Any]:
    try:
        aliases = json.loads(r.suggested_aliases) if r.suggested_aliases else []
    except json.JSONDecodeError:
        aliases = []
    return {
        "entity_id": r.entity_id, "status": r.status, "domain": r.domain,
        "friendly_name": r.friendly_name, "category": r.category, "room": r.room,
        "risk_level": r.risk_level, "suggested_aliases": aliases,
        "reason": r.reason, "is_available": r.is_available,
        "ignore_reason": r.ignore_reason,
    }


# --------------------------------------------------------------------------
# Approve / ignore / map (write overlay + update DB)
# --------------------------------------------------------------------------
def approve(entity_id: str, mapping: str = "device_aliases",
            room: Optional[str] = None, friendly_name: Optional[str] = None,
            aliases: Optional[list[str]] = None) -> dict[str, Any]:
    domain = entity_id.split(".", 1)[0]
    name = friendly_name or _slug(entity_id).replace("_", " ").title()
    aliases = aliases or [name.lower()]
    overlay = read_overlay()

    entry: dict[str, Any]
    if mapping == "cameras":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "aliases": aliases}
    elif mapping == "locks":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "aliases": aliases}
    elif mapping == "speakers":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "room": room, "aliases": aliases}
    elif mapping == "displays":
        entry = {"id": _slug(entity_id), "name": name, "type": "media_player",
                 "entity_id": entity_id, "aliases": aliases}
    elif mapping == "climate":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "room": room, "aliases": aliases}
    elif mapping == "security_sensors":
        entry = {"entity_id": entity_id, "name": name, "aliases": aliases}
    elif mapping == "personal_devices":
        platform = "ios" if any(k in entity_id.lower() for k in ("iphone", "ipad")) else None
        device_type = "phone" if "iphone" in entity_id.lower() else (
            "tablet" if "ipad" in entity_id.lower() else "personal_device"
        )
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "owner": None, "platform": platform, "device_type": device_type,
                 "room": room, "aliases": aliases}
    else:
        mapping = "device_aliases"
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "domain": domain, "room": room, "aliases": aliases}

    section = overlay.setdefault(mapping, [])
    section[:] = [e for e in section if e.get("entity_id") != entity_id]
    section.append(entry)
    # Approving removes any prior ignore of this entity.
    for key in ("avoid", "ignored"):
        if key in overlay:
            overlay[key] = [e for e in overlay[key]
                            if (e if isinstance(e, str) else e.get("entity_id")) != entity_id]
    write_overlay(overlay)

    _set_status(entity_id, "approved", room=room or "", friendly=name,
                aliases=aliases, mapping=mapping)
    logger.info("Approved %s into %s", entity_id, mapping)
    return {"entity_id": entity_id, "mapping": mapping, "entry": entry}


def ignore(entity_id: str, reason: str = "") -> dict[str, Any]:
    overlay = read_overlay()
    avoid = overlay.setdefault("avoid", [])
    if entity_id not in avoid:
        avoid.append(entity_id)
    ignored = overlay.setdefault("ignored", [])
    ignored[:] = [e for e in ignored if (e.get("entity_id") if isinstance(e, dict) else e) != entity_id]
    ignored.append({"entity_id": entity_id, "reason": reason})
    write_overlay(overlay)
    _set_status(entity_id, "ignored", ignore_reason=reason)
    logger.info("Ignored %s (%s)", entity_id, reason or "no reason")
    return {"entity_id": entity_id, "reason": reason}


def _set_status(entity_id: str, status: str, room: str = "", friendly: str = "",
                aliases: Optional[list[str]] = None, mapping: str = "",
                ignore_reason: str = "") -> None:
    with get_session() as session:
        row = session.get(DiscoveredEntity, entity_id)
        if row is None:
            row = DiscoveredEntity(entity_id=entity_id,
                                   domain=entity_id.split(".", 1)[0])
            session.add(row)
        row.status = status
        if room:
            row.room = room
        if friendly:
            row.friendly_name = friendly
        if aliases is not None:
            row.suggested_aliases = json.dumps(aliases)
        if mapping:
            row.category = row.category or mapping
        if ignore_reason:
            row.ignore_reason = ignore_reason
        session.commit()
