"""Discovery registry: persists discovered-entity state in SQLite and writes
approved mappings / ignores to a generated overlay file (config/discovered.yaml)
that the config loader merges into devices.yaml.

We never edit the hand-written devices.yaml in place (preserves comments). We
never auto-delete or auto-ignore; ignores only happen on explicit user action.
"""
from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any, Optional

import yaml

from ..db.database import get_session
from ..db.models import DiscoveredEntity
from ..entity_intelligence import (
    browser_mod_role,
    is_browser_mod_entity,
    smart_entity_name,
    unavailable_diagnosis,
)
from ..models.schemas import HAEntity
from ..settings import get_settings
from .classifier import EntityClassification

logger = logging.getLogger("tpg.discovery.registry")

DISCOVERED_FILE = "discovered.yaml"
_LIST_SECTIONS = ["device_aliases", "cameras", "locks", "speakers", "displays",
                  "climate", "security_sensors", "personal_devices", "avoid",
                  "ignored"]


def _overlay_path() -> Path:
    return get_settings().config_path / DISCOVERED_FILE


def read_overlay() -> dict[str, Any]:
    path = _overlay_path()
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def write_overlay(data: dict[str, Any]) -> None:
    path = _overlay_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by TPG HomeAI discovery approvals. Safe to edit, "
                 "but it is merged into devices.yaml at load time.\n")
        yaml.safe_dump(data, fh, sort_keys=False, allow_unicode=True)


def _slug(entity_id: str) -> str:
    base = entity_id.split(".", 1)[-1]
    return re.sub(r"[^a-z0-9_]+", "_", base.lower()).strip("_") or "device"


def _humanize_slug(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("_", " ")).strip().title()


def _room_name(room_id: str) -> str:
    try:
        from ..config_loader import get_config

        for room in get_config().devices.rooms:
            if room.id == room_id:
                return room.name
    except Exception:  # noqa: BLE001 - discovery should still write overlay
        pass
    return _humanize_slug(room_id)


def _derive_device_name(entity_id: str, friendly: str = "") -> str:
    text = f"{entity_id} {friendly}".lower()
    mobile_match = re.search(r"(tpg[ _-]*)?(iphone|ipad|watch|android)[ _-]*([a-z0-9]+)?", text)
    if mobile_match:
        prefix = "TPG " if mobile_match.group(1) else ""
        kind = mobile_match.group(2)
        suffix = mobile_match.group(3) or ""
        display_kind = {"iphone": "iPhone", "ipad": "iPad", "android": "Android",
                        "watch": "Watch"}.get(kind, kind.title())
        return f"{prefix}{display_kind}{suffix}"
    if entity_id.startswith("person."):
        return friendly or _humanize_slug(entity_id.split(".", 1)[-1])
    if friendly:
        words = friendly.split()
        if len(words) >= 2 and words[0].lower() == words[1].lower():
            return words[0].title()
        if words:
            return words[0] if len(words) > 2 else friendly
    return _humanize_slug(entity_id.split(".", 1)[-1])


def _semantic_category(entity_id: str, domain: str, category: str = "",
                       friendly: str = "") -> str:
    text = f"{entity_id} {friendly} {category}".lower()
    if is_browser_mod_entity(entity_id, friendly):
        role = browser_mod_role(HAEntity(
            entity_id=entity_id,
            state="unknown",
            friendly_name=friendly,
            domain=domain,
            available=False,
        ))
        return "browser_mod_panel" if role in {"panel_screen", "panel_speaker"} else "browser_mod_diagnostic"
    if category == "personal_device" and domain in {"sensor", "binary_sensor"}:
        return "personal_device_sensor"
    if category == "personal_device" or domain == "device_tracker":
        return "personal_device"
    if category == "personal_device_sensor":
        return "personal_device_sensor"
    if domain in {"sensor", "binary_sensor"} and any(
        h in text for h in (
            "app_version", "app version", "bssid", "ssid", "sim_1", "sim 1",
            "sim_2", "sim 2", "audio_output", "audio output",
            "location_permission", "location permission", "geocoded_location",
            "geocoded location", "last_update", "last update",
        )
    ):
        return "personal_device_sensor"
    if domain == "person":
        return "person"
    if "backup" in text:
        return "system_backup"
    if any(h in text for h in ("bssid", "ssid", "connection", "router", "eero", "wan", "internet")):
        return "network"
    if any(h in text for h in (
        "app_version", "app version", "audio_output", "audio output",
        "location_permission", "location permission", "geocoded_location",
        "geocoded location", "last_update", "last update", "sim_1", "sim 1",
        "sim_2", "sim 2",
    )):
        return "diagnostic_sensor"
    return category or domain or "other"


def _suggested_mapping(category: str, domain: str) -> str:
    if domain == "light":
        return "lights"
    if domain == "fan":
        return "fans"
    if category == "person" or domain == "person":
        return "person"
    if category == "personal_device":
        return "personal_devices"
    if domain == "camera":
        return "cameras"
    if domain == "lock":
        return "locks"
    if domain == "media_player":
        return "speakers"
    if domain == "climate":
        return "climate"
    if domain == "binary_sensor":
        return "security_sensors"
    return "device_aliases"


def _approval_label(mapping: str, semantic: str, domain: str) -> str:
    if mapping == "lights":
        return "Approve as light"
    if mapping == "fans":
        return "Approve as fan"
    if mapping == "person":
        return "Approve as person"
    if mapping == "personal_devices":
        return "Map as personal device"
    if semantic == "browser_mod_panel":
        return "Approve as panel control"
    if semantic == "browser_mod_diagnostic":
        return "Approve as panel diagnostic"
    if semantic in {"diagnostic_sensor", "personal_device_sensor", "network", "system_backup"}:
        return "Approve as diagnostic"
    if domain == "switch":
        return "Approve as switch"
    return "Approve as status"


def _auto_approvable(domain: str, semantic: str, risk: str, duplicate: bool) -> bool:
    if duplicate or risk in {"high", "critical"}:
        return False
    if semantic in {"browser_mod_panel", "browser_mod_diagnostic"}:
        return False
    if semantic in {"diagnostic_sensor", "personal_device_sensor", "network", "system_backup"}:
        return False
    return domain in {"light", "fan", "person", "device_tracker"} or semantic == "personal_device"


# --------------------------------------------------------------------------
# SQLite sync of classifications
# --------------------------------------------------------------------------
def sync_classifications(classifications: list[EntityClassification]) -> None:
    """Upsert discovery rows. Preserves user decisions (approved/ignored)."""
    with get_session() as session:
        existing = {d.entity_id: d for d in session.query(DiscoveredEntity).all()}
        for c in classifications:
            row = existing.get(c.entity_id)
            if row is None:
                row = DiscoveredEntity(entity_id=c.entity_id)
                session.add(row)
            # Keep a previously-decided status (approved/ignored) sticky.
            decided = row.status in ("approved", "ignored")
            row.domain = c.domain
            row.friendly_name = c.friendly_name
            row.category = c.suggested_category
            if not decided:
                row.room = c.likely_room or ""
                row.risk_level = c.risk_level
                row.suggested_aliases = json.dumps(c.suggested_aliases)
                row.reason = c.reason
                row.status = "known" if c.status == "known" else (
                    row.status if row.status in ("approved", "ignored") else c.status)
            row.is_available = c.is_available
        session.commit()


def get_pending() -> list[dict[str, Any]]:
    with get_session() as session:
        rows = session.query(DiscoveredEntity).filter(
            DiscoveredEntity.status == "new").all()
        return _row_dicts(rows)


def get_all() -> list[dict[str, Any]]:
    with get_session() as session:
        return _row_dicts(session.query(DiscoveredEntity).all())


def _row_dicts(rows: list[DiscoveredEntity]) -> list[dict[str, Any]]:
    all_ids = [r.entity_id for r in rows]
    return [_row_dict(r, all_ids) for r in rows]


def _row_dict(r: DiscoveredEntity, all_entity_ids: Optional[list[str]] = None) -> dict[str, Any]:
    try:
        aliases = json.loads(r.suggested_aliases) if r.suggested_aliases else []
    except json.JSONDecodeError:
        aliases = []
    semantic = _semantic_category(r.entity_id, r.domain or "", r.category or "",
                                  r.friendly_name or "")
    device_name = _derive_device_name(r.entity_id, r.friendly_name or "")
    suggested_mapping = _suggested_mapping(semantic, r.domain or "")
    duplicate = "possible duplicate" in (r.reason or "").lower()
    state = "unknown" if r.is_available else "unavailable"
    entity = HAEntity(
        entity_id=r.entity_id,
        state=state,
        friendly_name=r.friendly_name or "",
        domain=r.domain or r.entity_id.split(".", 1)[0],
        available=bool(r.is_available),
    )
    sibling_states = {
        eid: HAEntity(
            entity_id=eid,
            state="unknown",
            friendly_name="",
            domain=eid.split(".", 1)[0],
            available=False,
        )
        for eid in (all_entity_ids or [])
        if eid != r.entity_id
    }
    smart = smart_entity_name(
        r.entity_id,
        r.domain or "",
        r.friendly_name or "",
        room_id=r.room or None,
        siblings=(all_entity_ids or []),
    )
    if smart.get("aliases"):
        aliases = list(dict.fromkeys([*smart["aliases"], *aliases]))
    if (r.domain or "") == "light" and "domain is light" in str(smart.get("rename_reason") or ""):
        aliases = [a for a in aliases if " fan" not in f" {a} "]
    elif (r.domain or "") == "fan" and "domain is fan" in str(smart.get("rename_reason") or ""):
        aliases = [a for a in aliases if " light" not in f" {a} "]
    if r.room and (r.domain or "") in {"light", "fan", "switch"}:
        aliases = [a for a in aliases if a != r.room.replace("_", " ").lower()]
    health = unavailable_diagnosis(entity, sibling_states)
    browser_role = browser_mod_role(entity)
    return {
        "entity_id": r.entity_id, "status": r.status, "domain": r.domain,
        "friendly_name": r.friendly_name, "category": r.category,
        "suggested_name": smart.get("name") or r.friendly_name,
        "smart_aliases": smart.get("aliases", []),
        "rename_recommended": bool(smart.get("rename_recommended")),
        "rename_reason": smart.get("rename_reason") or "",
        "suggested_category": r.category, "semantic_category": semantic,
        "room": r.room, "likely_room": r.room,
        "device_name": device_name, "source": "Home Assistant",
        "source_detail": "Home Assistant entity state registry (/api/states)",
        "suggested_mapping": suggested_mapping,
        "approval_label": _approval_label(suggested_mapping, semantic, r.domain or ""),
        "auto_approvable": bool(r.is_available) and _auto_approvable(
            r.domain or "", semantic, r.risk_level or "low", duplicate
        ),
        "confidence": 1.0 if r.domain else 0.65,
        "risk_level": r.risk_level, "suggested_aliases": aliases,
        "reason": r.reason, "is_available": r.is_available,
        "browser_mod_role": browser_role,
        "health": health,
        "unavailable_reason": health.get("reason", "") if not r.is_available else "",
        "recommended_action": health.get("recommended_action", ""),
        "is_duplicate_candidate": duplicate,
        "ignore_reason": r.ignore_reason,
    }


def _upsert_device_alias(overlay: dict[str, Any], entry: dict[str, Any]) -> None:
    section = overlay.setdefault("device_aliases", [])
    section[:] = [e for e in section if e.get("entity_id") != entry.get("entity_id")]
    section.append(entry)


def _upsert_room_member(overlay: dict[str, Any], room: Optional[str],
                        field: str, entity_id: str) -> None:
    if not room:
        return
    rooms = overlay.setdefault("rooms", [])
    room_entry = next((r for r in rooms if isinstance(r, dict) and r.get("id") == room), None)
    if room_entry is None:
        room_entry = {"id": room, "name": _room_name(room), "aliases": [], "lights": [], "fans": []}
        rooms.append(room_entry)
    values = room_entry.setdefault(field, [])
    if entity_id not in values:
        values.append(entity_id)


# --------------------------------------------------------------------------
# Approve / ignore / map (write overlay + update DB)
# --------------------------------------------------------------------------
def approve(entity_id: str, mapping: str = "device_aliases",
            room: Optional[str] = None, friendly_name: Optional[str] = None,
            aliases: Optional[list[str]] = None) -> dict[str, Any]:
    domain = entity_id.split(".", 1)[0]
    name = friendly_name or _slug(entity_id).replace("_", " ").title()
    aliases = aliases or [name.lower()]
    overlay = read_overlay()

    entry: dict[str, Any]
    if mapping == "cameras":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "aliases": aliases}
    elif mapping == "locks":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "aliases": aliases}
    elif mapping == "speakers":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "room": room, "aliases": aliases}
    elif mapping == "displays":
        entry = {"id": _slug(entity_id), "name": name, "type": "media_player",
                 "entity_id": entity_id, "aliases": aliases}
    elif mapping == "climate":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "room": room, "aliases": aliases}
    elif mapping == "security_sensors":
        entry = {"entity_id": entity_id, "name": name, "aliases": aliases}
    elif mapping == "personal_devices":
        platform = "ios" if any(k in entity_id.lower() for k in ("iphone", "ipad")) else None
        device_type = "phone" if "iphone" in entity_id.lower() else (
            "tablet" if "ipad" in entity_id.lower() else "personal_device"
        )
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "owner": None, "platform": platform, "device_type": device_type,
                 "room": room, "aliases": aliases}
    elif mapping in {"lights", "fans"}:
        category = "light" if mapping == "lights" else "fan"
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "domain": domain, "room": room, "category": category,
                 "aliases": aliases}
        _upsert_device_alias(overlay, entry)
        _upsert_room_member(overlay, room, mapping, entity_id)
        for key in ("avoid", "ignored"):
            if key in overlay:
                overlay[key] = [e for e in overlay[key]
                                if (e if isinstance(e, str) else e.get("entity_id")) != entity_id]
        write_overlay(overlay)
        _set_status(entity_id, "approved", room=room or "", friendly=name,
                    aliases=aliases, mapping=mapping)
        logger.info("Approved %s into %s", entity_id, mapping)
        return {"entity_id": entity_id, "mapping": mapping, "entry": entry}
    elif mapping == "person":
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "domain": domain, "room": None, "category": "person",
                 "aliases": aliases}
        _upsert_device_alias(overlay, entry)
        for key in ("avoid", "ignored"):
            if key in overlay:
                overlay[key] = [e for e in overlay[key]
                                if (e if isinstance(e, str) else e.get("entity_id")) != entity_id]
        write_overlay(overlay)
        _set_status(entity_id, "approved", room="", friendly=name,
                    aliases=aliases, mapping="person")
        logger.info("Approved %s into person", entity_id)
        return {"entity_id": entity_id, "mapping": "person", "entry": entry}
    else:
        mapping = "device_aliases"
        entry = {"id": _slug(entity_id), "name": name, "entity_id": entity_id,
                 "domain": domain, "room": room, "aliases": aliases}

    section = overlay.setdefault(mapping, [])
    section[:] = [e for e in section if e.get("entity_id") != entity_id]
    section.append(entry)
    # Approving removes any prior ignore of this entity.
    for key in ("avoid", "ignored"):
        if key in overlay:
            overlay[key] = [e for e in overlay[key]
                            if (e if isinstance(e, str) else e.get("entity_id")) != entity_id]
    write_overlay(overlay)

    _set_status(entity_id, "approved", room=room or "", friendly=name,
                aliases=aliases, mapping=mapping)
    logger.info("Approved %s into %s", entity_id, mapping)
    return {"entity_id": entity_id, "mapping": mapping, "entry": entry}


def ignore(entity_id: str, reason: str = "") -> dict[str, Any]:
    overlay = read_overlay()
    avoid = overlay.setdefault("avoid", [])
    if entity_id not in avoid:
        avoid.append(entity_id)
    ignored = overlay.setdefault("ignored", [])
    ignored[:] = [e for e in ignored if (e.get("entity_id") if isinstance(e, dict) else e) != entity_id]
    ignored.append({"entity_id": entity_id, "reason": reason})
    write_overlay(overlay)
    _set_status(entity_id, "ignored", ignore_reason=reason)
    logger.info("Ignored %s (%s)", entity_id, reason or "no reason")
    return {"entity_id": entity_id, "reason": reason}


def _set_status(entity_id: str, status: str, room: str = "", friendly: str = "",
                aliases: Optional[list[str]] = None, mapping: str = "",
                ignore_reason: str = "") -> None:
    with get_session() as session:
        row = session.get(DiscoveredEntity, entity_id)
        if row is None:
            row = DiscoveredEntity(entity_id=entity_id,
                                   domain=entity_id.split(".", 1)[0])
            session.add(row)
        row.status = status
        if room:
            row.room = room
        if friendly:
            row.friendly_name = friendly
        if aliases is not None:
            row.suggested_aliases = json.dumps(aliases)
        if mapping:
            row.category = row.category or mapping
        if ignore_reason:
            row.ignore_reason = ignore_reason
        session.commit()
